# Generated by Django 5.2.4 on 2025-08-04 04:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the food item', max_length=200)),
                ('calories', models.PositiveIntegerField(help_text='Calories per serving')),
                ('serving_size', models.CharField(default='1 serving', help_text='Description of serving size', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Food Item',
                'verbose_name_plural': 'Food Items',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='mealitem',
            name='food',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mealitem',
            name='meal',
        ),
        migrations.CreateModel(
            name='DailyCalorieLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, unique=True)),
                ('total_calories', models.PositiveIntegerField(default=0, help_text='Total calories consumed today')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Calorie Log',
                'verbose_name_plural': 'Daily Calorie Logs',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CalorieEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of servings')),
                ('calories_consumed', models.PositiveIntegerField(help_text='Total calories for this entry')),
                ('consumed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this entry')),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tracker.dailycalorielog')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.fooditem')),
            ],
            options={
                'verbose_name': 'Calorie Entry',
                'verbose_name_plural': 'Calorie Entries',
                'ordering': ['-consumed_at'],
            },
        ),
        migrations.DeleteModel(
            name='DailyLog',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
        migrations.DeleteModel(
            name='MealItem',
        ),
    ]
